# -*- coding: utf-8 -*-
"""CARS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-VaQxs9-ZmV5LJnInxwzuaEz605brCgR
"""

!nvidia-smi

!pip install ultralytics

import IPython
from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo checks

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="API")
project = rf.workspace("WORKSPACE").project("PROJECT")
dataset = project.version(1).download("yolov8")

!yolo detect train model=yolov8m.pt data={dataset.location}/data.yaml epochs=20 imgsz=640 workers=0 patience=50 verbose=False

!yolo detect val model=/content/runs/detect/train3/weights/best.pt data={dataset.location}/data.yaml

!yolo predict model=/content/runs/detect/train3/weights/best.pt source=/content/PKLot-2/custom/images/cars.jpg